# Generated by Django 2.2.4 on 2019-08-20 00:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktrader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cash',
            field=models.FloatField(default=10000, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
